name: hospital_queue_app
description: "Hospital queue and token management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Supabase (auth + data + edge functions)
  supabase_flutter: ^2.12.0

  # State management
  flutter_riverpod: ^3.3.2

  go_router: ^17.3.0

  cupertino_icons: ^1.0.8
  intl: ^0.20.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.0
  google_fonts: ^8.2.0
  flutter_dotenv: ^6.0.1
  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#0B5FA5"
  adaptive_icon_foreground: assets/icon/app_icon.png
  remove_alpha_ios: true
